using NovaCore.Core;
using NovaCore.Core.ReferenceFrames;
using System.Diagnostics;

var tests=new (string,Action)[]{("transform algebra",TransformAlgebra),("hierarchy and conversion",Hierarchy),("reference-frame graph",Graph),("ORB",Orb),("CCI/CCF",CciCcf),("rotating velocity",Velocity),("validation",Validation)};
foreach(var (name,test) in tests){test();Console.WriteLine($"PASS {name}");}
Benchmark();

static void TransformAlgebra(){var t=new FrameTransform(new Double3(5,0,0),DoubleQuaternion.FromAxisAngle(Double3.UnitZ,Math.PI/2));var p=new Double3(1,0,0);Near(t.ParentToLocal(t.LocalToParent(p)),p);Near(Double3.Cross(Double3.UnitX,Double3.UnitY),Double3.UnitZ);}
static void Hierarchy(){var root=new ReferenceFrameId(1);var child=new ReferenceFrameId(2);var snap=new ReferenceFrameSnapshot([(new ReferenceFrameDefinition(root,null,ReferenceFrameKind.Ecl,"ECL"),CelestialFrameFactory.RootEcl()),(new ReferenceFrameDefinition(child,root,ReferenceFrameKind.Cce,"CCE"),CelestialFrameFactory.Cce(new Double3(4e12,0,0),Double3.Zero))]);var r=new ReferenceFrameResolver(snap);Check(r.TryResolvePosition(new FramePosition(child,new Double3(.25,0,0)),out var world),"resolve");Near(world.Value,new Double3(4e12+.25,0,0));Check(r.TryConvertPosition(new FramePosition(child,new Double3(.25,0,0)),root,out var converted),"convert");Near(converted.Value,world.Value);}
static void Graph(){var root=new ReferenceFrameId(1);var first=new ReferenceFrameId(2);var second=new ReferenceFrameId(3);var grandchild=new ReferenceFrameId(4);var builder=new ReferenceFrameGraphBuilder();builder.Add(new ReferenceFrameNode(root,null,ReferenceFrameKind.Ecl,"root"));builder.Add(new ReferenceFrameNode(first,root,ReferenceFrameKind.Cce,"first"));builder.Add(new ReferenceFrameNode(second,root,ReferenceFrameKind.Orb,"second"));builder.Add(new ReferenceFrameNode(grandchild,first,ReferenceFrameKind.Cci,"grandchild"));var graph=builder.Build();Check(graph.Count==4&&graph.RootCount==1&&graph.TryGetNode(second,out var node)&&node.DiagnosticName=="second","graph lookup");Check(graph.TryGetParent(grandchild,out var parent)&&parent.Id==first&&graph.IsAncestorOf(root,grandchild)&&graph.IsAncestorOf(first,grandchild)&&!graph.IsAncestorOf(grandchild,grandchild),"graph ancestry");var children="";foreach(var child in graph.GetChildren(root))children+=child.Id.Value+",";Check(children=="2,3,","graph child insertion order");var traversal="";foreach(var frame in graph.TraverseDepthFirst())traversal+=frame.Id.Value+",";Check(traversal=="1,2,4,3,","graph depth-first order");var ancestors="";foreach(var ancestor in graph.GetAncestors(grandchild))ancestors+=ancestor.Id.Value+",";Check(ancestors=="2,1,","graph parent-first ancestry order");Throws<ArgumentException>(()=>builder.Add(new ReferenceFrameNode(first,root,ReferenceFrameKind.Cce,"duplicate")));Throws<ArgumentException>(()=>new ReferenceFrameGraphBuilder().Add(new ReferenceFrameNode(first,root,ReferenceFrameKind.Cce,"missing parent")));var before=GC.GetAllocatedBytesForCurrentThread();for(var i=0;i<100_000;i++){foreach(var _ in graph.GetChildren(root)){}foreach(var _ in graph.TraverseDepthFirst()){}foreach(var _ in graph.GetAncestors(grandchild)){}_=graph.IsAncestorOf(root,grandchild);}_=graph.TryGetParent(grandchild,out _);Check(GC.GetAllocatedBytesForCurrentThread()==before,"graph traversal allocates zero bytes");}
static void Orb(){var q=new OrbitalFrameGeometry(0,0,0).ToEclRotation();Near(q.Rotate(Double3.UnitX),Double3.UnitX);Near(q.Rotate(Double3.UnitZ),Double3.UnitZ);var z=new OrbitalFrameGeometry(Math.PI/2,0,0).ToEclRotation().Rotate(Double3.UnitZ);Near(z,new Double3(0,-1,0));}
static void CciCcf(){var cci=CelestialFrameFactory.Cci(Double3.Zero,Double3.Zero,Double3.UnitZ,Double3.UnitX);Near(cci.LocalToParent.Rotation.Rotate(Double3.UnitZ),Double3.UnitZ);var ccf=CelestialFrameFactory.Ccf(Math.PI/2,1);Near(ccf.LocalToParent.Rotation.Rotate(Double3.UnitX),Double3.UnitY);try{CelestialFrameFactory.Cci(Double3.Zero,Double3.Zero,Double3.UnitZ,Double3.UnitZ);throw new Exception("degeneracy accepted");}catch(ArgumentException){}}
static void Velocity(){var root=new ReferenceFrameId(1);var rotating=new ReferenceFrameId(2);var s=new ReferenceFrameSnapshot([(new ReferenceFrameDefinition(root,null,ReferenceFrameKind.Ecl,"ECL"),CelestialFrameFactory.RootEcl()),(new ReferenceFrameDefinition(rotating,root,ReferenceFrameKind.Ccf,"CCF"),CelestialFrameFactory.Ccf(0,2))]);var r=new ReferenceFrameResolver(s);Check(r.TryConvertVelocity(new FramePosition(rotating,new Double3(3,0,0)),new FrameVelocity(rotating,Double3.Zero),root,out var v),"velocity");Near(v.Value,new Double3(0,6,0));}
static void Validation(){var root=new ReferenceFrameId(1);var child=new ReferenceFrameId(2);try{_ = new ReferenceFrameSnapshot([(new ReferenceFrameDefinition(root,child,ReferenceFrameKind.Ecl,"E"),CelestialFrameFactory.RootEcl()),(new ReferenceFrameDefinition(child,root,ReferenceFrameKind.Cce,"C"),CelestialFrameFactory.Cce(Double3.Zero,Double3.Zero))]);throw new Exception("cycle accepted");}catch(ArgumentException){}try{_ = new ReferenceFrameSnapshot([(new ReferenceFrameDefinition(root,null,ReferenceFrameKind.Cce,"bad"),CelestialFrameFactory.RootEcl())]);throw new Exception("bad root accepted");}catch(ArgumentException){}}
static void Near(Double3 a,Double3 b){if((a-b).LengthSquared>1e-18)throw new Exception($"Expected {b}, got {a}");}
static void Check(bool value,string text){if(!value)throw new Exception(text);}
static void Throws<T>(Action action) where T:Exception{try{action();throw new Exception($"Expected {typeof(T).Name}");}catch(T){}}
static void Benchmark(){var root=new ReferenceFrameId(1);var child=new ReferenceFrameId(2);var s=new ReferenceFrameSnapshot([(new ReferenceFrameDefinition(root,null,ReferenceFrameKind.Ecl,"ECL"),CelestialFrameFactory.RootEcl()),(new ReferenceFrameDefinition(child,root,ReferenceFrameKind.Cce,"CCE"),CelestialFrameFactory.Cce(new Double3(4e12,0,0),Double3.Zero))]);var r=new ReferenceFrameResolver(s);r.TryResolvePosition(new FramePosition(child,Double3.Zero),out _);var watch=new Stopwatch();var before=GC.GetAllocatedBytesForCurrentThread();watch.Start();UniversePosition p=default;for(var i=0;i<10000;i++)r.TryResolvePosition(new FramePosition(child,new Double3(i*.001,0,0)),out p);watch.Stop();var allocated=GC.GetAllocatedBytesForCurrentThread()-before;Console.WriteLine($"Benchmark: 10,000 root resolutions in {watch.Elapsed.TotalMilliseconds:F3} ms; managed allocations={allocated} bytes; final={p.Value.X:R}");Check(allocated==0,"resolver allocated during repeated resolution");}
