<Project Sdk="Microsoft.NET.Sdk"><ItemGroup><ProjectReference Include="..\NovaCore.Core\NovaCore.Core.csproj" /><ProjectReference Include="..\NovaCore.EphemerisFormat\NovaCore.EphemerisFormat.csproj" /><EmbeddedResource Include="Celestial\Data\moon_me_de440_1900_2100.nclo" LogicalName="NovaCore.Simulation.Celestial.Data.moon_me_de440_1900_2100.nclo" /></ItemGroup></Project>
