#include "NovaCoreNative.h"
#include <vulkan/vulkan.h>
#include <windows.h>
#include <algorithm>
#include <array>
#include <chrono>
#include <cstdio>
#include <cstring>
#include <fstream>
#include <optional>
#include <string>
#include <vector>

namespace {
constexpr uint32_t Width = 960, Height = 540;
struct QueueFamilies { std::optional<uint32_t> graphics, present; bool Complete() const { return graphics && present; } };
struct App {
  NcDiagnosticCallback callback{}; void* callbackData{}; HWND window{}; VkInstance instance{}; VkDebugUtilsMessengerEXT debug{}; VkSurfaceKHR surface{};
  VkPhysicalDevice physical{}; VkDevice device{}; VkQueue graphicsQueue{}, presentQueue{}; VkSwapchainKHR swapchain{}; VkFormat swapFormat{}; VkExtent2D extent{};
  std::vector<VkImage> images; std::vector<VkImageView> views; VkRenderPass renderPass{}; VkPipelineLayout pipelineLayout{}; VkPipeline pipeline{};
  std::vector<VkFramebuffer> framebuffers; VkCommandPool commandPool{}; std::vector<VkCommandBuffer> commands; VkSemaphore imageAvailable{}; std::vector<VkSemaphore> renderFinished; VkFence inFlight{}; bool resized{}; NcRelativePosition position{};
  void Log(const char* text) const { if (callback) callback(text, callbackData); }
  void Check(VkResult r, const char* what) { if (r != VK_SUCCESS) { Log(what); throw std::runtime_error(what); } }
};
App* gApp{};
LRESULT CALLBACK WindowProc(HWND h, UINT m, WPARAM w, LPARAM l) { if (m == WM_SIZE && gApp) gApp->resized = true; if (m == WM_CLOSE) DestroyWindow(h); if (m == WM_DESTROY) PostQuitMessage(0); return DefWindowProc(h,m,w,l); }
VKAPI_ATTR VkBool32 VKAPI_CALL DebugCallback(VkDebugUtilsMessageSeverityFlagBitsEXT, VkDebugUtilsMessageTypeFlagsEXT, const VkDebugUtilsMessengerCallbackDataEXT* d, void* u) { static_cast<App*>(u)->Log(d->pMessage); return VK_FALSE; }
void CreateNativeWindow(App& a) { WNDCLASSW wc{.lpfnWndProc=WindowProc,.hInstance=GetModuleHandleW(nullptr),.lpszClassName=L"NovaCoreWindow"}; RegisterClassW(&wc); a.window=CreateWindowExW(0,wc.lpszClassName,L"NovaCore - Vulkan Triangle",WS_OVERLAPPEDWINDOW,CW_USEDEFAULT,CW_USEDEFAULT,Width,Height,nullptr,nullptr,wc.hInstance,nullptr); if(!a.window) throw std::runtime_error("CreateWindowExW failed"); ShowWindow(a.window,SW_SHOW); }
std::vector<const char*> InstanceExtensions() {
  std::vector<const char*> v{VK_KHR_SURFACE_EXTENSION_NAME,VK_KHR_WIN32_SURFACE_EXTENSION_NAME};
#ifdef NC_DEBUG_BUILD
  v.push_back(VK_EXT_DEBUG_UTILS_EXTENSION_NAME);
#endif
  return v;
}
void CreateInstance(App& a) { VkApplicationInfo ai{VK_STRUCTURE_TYPE_APPLICATION_INFO,nullptr,"NovaCore",1,"NovaCore",1,VK_API_VERSION_1_0}; auto ext=InstanceExtensions(); VkInstanceCreateInfo ci{VK_STRUCTURE_TYPE_INSTANCE_CREATE_INFO}; ci.pApplicationInfo=&ai;ci.enabledExtensionCount=(uint32_t)ext.size();ci.ppEnabledExtensionNames=ext.data();
#ifdef NC_DEBUG_BUILD
  const char* layer="VK_LAYER_KHRONOS_validation";ci.enabledLayerCount=1;ci.ppEnabledLayerNames=&layer;
#endif
  a.Check(vkCreateInstance(&ci,nullptr,&a.instance),"vkCreateInstance failed"); a.Log("Vulkan instance created"); }
void CreateDebug(App& a) {
#ifdef NC_DEBUG_BUILD
  VkDebugUtilsMessengerCreateInfoEXT ci{VK_STRUCTURE_TYPE_DEBUG_UTILS_MESSENGER_CREATE_INFO_EXT};ci.messageSeverity=VK_DEBUG_UTILS_MESSAGE_SEVERITY_WARNING_BIT_EXT|VK_DEBUG_UTILS_MESSAGE_SEVERITY_ERROR_BIT_EXT;ci.messageType=VK_DEBUG_UTILS_MESSAGE_TYPE_GENERAL_BIT_EXT|VK_DEBUG_UTILS_MESSAGE_TYPE_VALIDATION_BIT_EXT|VK_DEBUG_UTILS_MESSAGE_TYPE_PERFORMANCE_BIT_EXT;ci.pfnUserCallback=DebugCallback;ci.pUserData=&a;auto fn=(PFN_vkCreateDebugUtilsMessengerEXT)vkGetInstanceProcAddr(a.instance,"vkCreateDebugUtilsMessengerEXT");if(fn)a.Check(fn(a.instance,&ci,nullptr,&a.debug),"debug messenger failed");
#endif
}
void CreateSurface(App& a) { VkWin32SurfaceCreateInfoKHR ci{VK_STRUCTURE_TYPE_WIN32_SURFACE_CREATE_INFO_KHR,nullptr,0,GetModuleHandleW(nullptr),a.window};a.Check(vkCreateWin32SurfaceKHR(a.instance,&ci,nullptr,&a.surface),"surface creation failed"); }
QueueFamilies FindQueues(VkPhysicalDevice d, VkSurfaceKHR s) { QueueFamilies q;uint32_t n=0;vkGetPhysicalDeviceQueueFamilyProperties(d,&n,nullptr);std::vector<VkQueueFamilyProperties> p(n);vkGetPhysicalDeviceQueueFamilyProperties(d,&n,p.data());for(uint32_t i=0;i<n;i++){if(p[i].queueFlags&VK_QUEUE_GRAPHICS_BIT)q.graphics=i;VkBool32 present;vkGetPhysicalDeviceSurfaceSupportKHR(d,i,s,&present);if(present)q.present=i;}return q; }
bool Suitable(VkPhysicalDevice d,VkSurfaceKHR s){auto q=FindQueues(d,s);uint32_t n=0;vkEnumerateDeviceExtensionProperties(d,nullptr,&n,nullptr);std::vector<VkExtensionProperties> e(n);vkEnumerateDeviceExtensionProperties(d,nullptr,&n,e.data());return q.Complete()&&std::any_of(e.begin(),e.end(),[](auto& x){return std::strcmp(x.extensionName,VK_KHR_SWAPCHAIN_EXTENSION_NAME)==0;});}
void ReportGpu(App& a){VkPhysicalDeviceProperties p;vkGetPhysicalDeviceProperties(a.physical,&p);char b[512];std::snprintf(b,sizeof b,"GPU: %s | vendor: 0x%04X | device: 0x%04X | driver: %u | API: %u.%u.%u",p.deviceName,p.vendorID,p.deviceID,p.driverVersion,VK_VERSION_MAJOR(p.apiVersion),VK_VERSION_MINOR(p.apiVersion),VK_VERSION_PATCH(p.apiVersion));a.Log(b);auto q=FindQueues(a.physical,a.surface);std::snprintf(b,sizeof b,"Queue families: graphics=%u present=%u",*q.graphics,*q.present);a.Log(b);VkPhysicalDeviceMemoryProperties m;vkGetPhysicalDeviceMemoryProperties(a.physical,&m);for(uint32_t i=0;i<m.memoryHeapCount;i++){std::snprintf(b,sizeof b,"Memory heap %u: %llu MiB",i,(unsigned long long)(m.memoryHeaps[i].size/(1024*1024)));a.Log(b);}a.Log("Enabled extensions: VK_KHR_surface, VK_KHR_win32_surface, VK_KHR_swapchain");
#ifdef NC_DEBUG_BUILD
  a.Log("Enabled extension: VK_EXT_debug_utils");
  a.Log("Enabled layer: VK_LAYER_KHRONOS_validation");
#endif
}
void PickDevice(App& a){uint32_t n=0;vkEnumeratePhysicalDevices(a.instance,&n,nullptr);if(!n)throw std::runtime_error("No Vulkan physical devices");std::vector<VkPhysicalDevice>d(n);vkEnumeratePhysicalDevices(a.instance,&n,d.data());for(auto x:d){VkPhysicalDeviceProperties p;vkGetPhysicalDeviceProperties(x,&p);if(Suitable(x,a.surface)&&std::string(p.deviceName).find("AMD Radeon RX 6800 XT")!=std::string::npos){a.physical=x;a.Log("Selected preferred AMD Radeon RX 6800 XT");break;}}if(!a.physical){for(auto x:d)if(Suitable(x,a.surface)){a.physical=x;break;}a.Log("Preferred GPU unavailable; selected first suitable Vulkan device");}if(!a.physical)throw std::runtime_error("No suitable Vulkan device");ReportGpu(a);}
void CreateDevice(App& a){auto q=FindQueues(a.physical,a.surface);std::vector<uint32_t> ids{*q.graphics};if(*q.present!=*q.graphics)ids.push_back(*q.present);float priority=1;std::vector<VkDeviceQueueCreateInfo> qs;for(auto id:ids)qs.push_back({VK_STRUCTURE_TYPE_DEVICE_QUEUE_CREATE_INFO,nullptr,0,id,1,&priority});const char* ext=VK_KHR_SWAPCHAIN_EXTENSION_NAME;VkDeviceCreateInfo ci{VK_STRUCTURE_TYPE_DEVICE_CREATE_INFO};ci.queueCreateInfoCount=(uint32_t)qs.size();ci.pQueueCreateInfos=qs.data();ci.enabledExtensionCount=1;ci.ppEnabledExtensionNames=&ext;a.Check(vkCreateDevice(a.physical,&ci,nullptr,&a.device),"logical device failed");vkGetDeviceQueue(a.device,*q.graphics,0,&a.graphicsQueue);vkGetDeviceQueue(a.device,*q.present,0,&a.presentQueue);}
VkSurfaceFormatKHR SurfaceFormat(App&a){uint32_t n;vkGetPhysicalDeviceSurfaceFormatsKHR(a.physical,a.surface,&n,nullptr);std::vector<VkSurfaceFormatKHR> f(n);vkGetPhysicalDeviceSurfaceFormatsKHR(a.physical,a.surface,&n,f.data());for(auto x:f)if(x.format==VK_FORMAT_B8G8R8A8_SRGB&&x.colorSpace==VK_COLOR_SPACE_SRGB_NONLINEAR_KHR)return x;return f[0];}
void DestroySwap(App&a){for(auto x:a.framebuffers)vkDestroyFramebuffer(a.device,x,nullptr);a.framebuffers.clear();if(a.pipeline)vkDestroyPipeline(a.device,a.pipeline,nullptr),a.pipeline={};if(a.pipelineLayout)vkDestroyPipelineLayout(a.device,a.pipelineLayout,nullptr),a.pipelineLayout={};if(a.renderPass)vkDestroyRenderPass(a.device,a.renderPass,nullptr),a.renderPass={};for(auto x:a.views)vkDestroyImageView(a.device,x,nullptr);a.views.clear();if(a.swapchain)vkDestroySwapchainKHR(a.device,a.swapchain,nullptr),a.swapchain={};}
std::vector<char> Read(const char* n){
  HMODULE module{};
  GetModuleHandleExA(GET_MODULE_HANDLE_EX_FLAG_FROM_ADDRESS | GET_MODULE_HANDLE_EX_FLAG_UNCHANGED_REFCOUNT,
                     reinterpret_cast<LPCSTR>(&Read), &module);
  char path[MAX_PATH]{}; GetModuleFileNameA(module, path, MAX_PATH);
  std::string fullPath(path); fullPath.resize(fullPath.find_last_of("\\/") + 1); fullPath += n;
  std::ifstream f(fullPath,std::ios::binary|std::ios::ate);if(!f)throw std::runtime_error("shader file missing");auto s=f.tellg();std::vector<char>b((size_t)s);f.seekg(0);f.read(b.data(),s);return b;
}
VkShaderModule Shader(App&a,const char*n){auto b=Read(n);VkShaderModuleCreateInfo ci{VK_STRUCTURE_TYPE_SHADER_MODULE_CREATE_INFO,nullptr,0,b.size(),reinterpret_cast<const uint32_t*>(b.data())};VkShaderModule m;a.Check(vkCreateShaderModule(a.device,&ci,nullptr,&m),"shader module failed");return m;}
void CreateSwap(App&a){VkSurfaceCapabilitiesKHR c;vkGetPhysicalDeviceSurfaceCapabilitiesKHR(a.physical,a.surface,&c);auto sf=SurfaceFormat(a);a.extent=c.currentExtent.width!=UINT32_MAX?c.currentExtent:VkExtent2D{Width,Height};a.extent.width=std::clamp(a.extent.width,c.minImageExtent.width,c.maxImageExtent.width);a.extent.height=std::clamp(a.extent.height,c.minImageExtent.height,c.maxImageExtent.height);uint32_t count=std::min(c.minImageCount+1,c.maxImageCount?c.maxImageCount:UINT32_MAX);auto q=FindQueues(a.physical,a.surface);uint32_t ids[]{*q.graphics,*q.present};VkSwapchainCreateInfoKHR ci{VK_STRUCTURE_TYPE_SWAPCHAIN_CREATE_INFO_KHR};ci.surface=a.surface;ci.minImageCount=count;ci.imageFormat=sf.format;ci.imageColorSpace=sf.colorSpace;ci.imageExtent=a.extent;ci.imageArrayLayers=1;ci.imageUsage=VK_IMAGE_USAGE_COLOR_ATTACHMENT_BIT;ci.imageSharingMode=*q.graphics==*q.present?VK_SHARING_MODE_EXCLUSIVE:VK_SHARING_MODE_CONCURRENT;ci.queueFamilyIndexCount=*q.graphics==*q.present?0:2;ci.pQueueFamilyIndices=ids;ci.preTransform=c.currentTransform;ci.compositeAlpha=VK_COMPOSITE_ALPHA_OPAQUE_BIT_KHR;ci.presentMode=VK_PRESENT_MODE_FIFO_KHR;ci.clipped=VK_TRUE;a.Check(vkCreateSwapchainKHR(a.device,&ci,nullptr,&a.swapchain),"swapchain failed");a.swapFormat=sf.format;uint32_t n;vkGetSwapchainImagesKHR(a.device,a.swapchain,&n,nullptr);a.images.resize(n);vkGetSwapchainImagesKHR(a.device,a.swapchain,&n,a.images.data());a.views.resize(n);for(uint32_t i=0;i<n;i++){VkImageViewCreateInfo vi{VK_STRUCTURE_TYPE_IMAGE_VIEW_CREATE_INFO};vi.image=a.images[i];vi.viewType=VK_IMAGE_VIEW_TYPE_2D;vi.format=a.swapFormat;vi.subresourceRange.aspectMask=VK_IMAGE_ASPECT_COLOR_BIT;vi.subresourceRange.levelCount=1;vi.subresourceRange.layerCount=1;a.Check(vkCreateImageView(a.device,&vi,nullptr,&a.views[i]),"image view failed");}
VkAttachmentDescription ad{};ad.format=a.swapFormat;ad.samples=VK_SAMPLE_COUNT_1_BIT;ad.loadOp=VK_ATTACHMENT_LOAD_OP_CLEAR;ad.storeOp=VK_ATTACHMENT_STORE_OP_STORE;ad.initialLayout=VK_IMAGE_LAYOUT_UNDEFINED;ad.finalLayout=VK_IMAGE_LAYOUT_PRESENT_SRC_KHR;VkAttachmentReference ar{0,VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL};VkSubpassDescription sub{};sub.pipelineBindPoint=VK_PIPELINE_BIND_POINT_GRAPHICS;sub.colorAttachmentCount=1;sub.pColorAttachments=&ar;VkRenderPassCreateInfo rp{VK_STRUCTURE_TYPE_RENDER_PASS_CREATE_INFO};rp.attachmentCount=1;rp.pAttachments=&ad;rp.subpassCount=1;rp.pSubpasses=&sub;a.Check(vkCreateRenderPass(a.device,&rp,nullptr,&a.renderPass),"render pass failed");
VkPushConstantRange pc{VK_SHADER_STAGE_VERTEX_BIT,0,12};VkPipelineLayoutCreateInfo pl{VK_STRUCTURE_TYPE_PIPELINE_LAYOUT_CREATE_INFO};pl.pushConstantRangeCount=1;pl.pPushConstantRanges=&pc;a.Check(vkCreatePipelineLayout(a.device,&pl,nullptr,&a.pipelineLayout),"pipeline layout failed");auto v=Shader(a,"shaders/triangle.vert.spv"),f=Shader(a,"shaders/triangle.frag.spv");VkPipelineShaderStageCreateInfo stages[2]{{VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO,nullptr,0,VK_SHADER_STAGE_VERTEX_BIT,v,"main"},{VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO,nullptr,0,VK_SHADER_STAGE_FRAGMENT_BIT,f,"main"}};VkPipelineVertexInputStateCreateInfo vi{VK_STRUCTURE_TYPE_PIPELINE_VERTEX_INPUT_STATE_CREATE_INFO};VkPipelineInputAssemblyStateCreateInfo ia{VK_STRUCTURE_TYPE_PIPELINE_INPUT_ASSEMBLY_STATE_CREATE_INFO,nullptr,0,VK_PRIMITIVE_TOPOLOGY_TRIANGLE_LIST};VkViewport vp{0,0,(float)a.extent.width,(float)a.extent.height,0,1};VkRect2D sc{{0,0},a.extent};VkPipelineViewportStateCreateInfo vs{VK_STRUCTURE_TYPE_PIPELINE_VIEWPORT_STATE_CREATE_INFO,nullptr,0,1,&vp,1,&sc};VkPipelineRasterizationStateCreateInfo rs{VK_STRUCTURE_TYPE_PIPELINE_RASTERIZATION_STATE_CREATE_INFO,nullptr,0,VK_FALSE,VK_FALSE,VK_POLYGON_MODE_FILL,VK_CULL_MODE_NONE,VK_FRONT_FACE_CLOCKWISE,VK_FALSE,0,0,0,1};VkPipelineMultisampleStateCreateInfo ms{VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO,nullptr,0,VK_SAMPLE_COUNT_1_BIT};VkPipelineColorBlendAttachmentState cb{VK_FALSE};cb.colorWriteMask=0xF;VkPipelineColorBlendStateCreateInfo bs{VK_STRUCTURE_TYPE_PIPELINE_COLOR_BLEND_STATE_CREATE_INFO,nullptr,0,VK_FALSE,VK_LOGIC_OP_COPY,1,&cb};VkGraphicsPipelineCreateInfo gp{VK_STRUCTURE_TYPE_GRAPHICS_PIPELINE_CREATE_INFO};gp.stageCount=2;gp.pStages=stages;gp.pVertexInputState=&vi;gp.pInputAssemblyState=&ia;gp.pViewportState=&vs;gp.pRasterizationState=&rs;gp.pMultisampleState=&ms;gp.pColorBlendState=&bs;gp.layout=a.pipelineLayout;gp.renderPass=a.renderPass;a.Check(vkCreateGraphicsPipelines(a.device,{},1,&gp,nullptr,&a.pipeline),"pipeline failed");vkDestroyShaderModule(a.device,v,nullptr);vkDestroyShaderModule(a.device,f,nullptr);a.framebuffers.resize(a.views.size());for(size_t i=0;i<a.views.size();i++){VkImageView x=a.views[i];VkFramebufferCreateInfo fb{VK_STRUCTURE_TYPE_FRAMEBUFFER_CREATE_INFO,nullptr,0,a.renderPass,1,&x,a.extent.width,a.extent.height,1};a.Check(vkCreateFramebuffer(a.device,&fb,nullptr,&a.framebuffers[i]),"framebuffer failed");}}
void CreateCommands(App&a){auto q=FindQueues(a.physical,a.surface);VkCommandPoolCreateInfo cp{VK_STRUCTURE_TYPE_COMMAND_POOL_CREATE_INFO,nullptr,VK_COMMAND_POOL_CREATE_RESET_COMMAND_BUFFER_BIT,*q.graphics};a.Check(vkCreateCommandPool(a.device,&cp,nullptr,&a.commandPool),"command pool failed");a.commands.resize(a.framebuffers.size());VkCommandBufferAllocateInfo al{VK_STRUCTURE_TYPE_COMMAND_BUFFER_ALLOCATE_INFO,nullptr,a.commandPool,VK_COMMAND_BUFFER_LEVEL_PRIMARY,(uint32_t)a.commands.size()};a.Check(vkAllocateCommandBuffers(a.device,&al,a.commands.data()),"command allocation failed");VkSemaphoreCreateInfo si{VK_STRUCTURE_TYPE_SEMAPHORE_CREATE_INFO};VkFenceCreateInfo fi{VK_STRUCTURE_TYPE_FENCE_CREATE_INFO,nullptr,VK_FENCE_CREATE_SIGNALED_BIT};a.Check(vkCreateSemaphore(a.device,&si,nullptr,&a.imageAvailable),"semaphore failed");a.renderFinished.resize(a.framebuffers.size());for(auto& semaphore:a.renderFinished)a.Check(vkCreateSemaphore(a.device,&si,nullptr,&semaphore),"semaphore failed");a.Check(vkCreateFence(a.device,&fi,nullptr,&a.inFlight),"fence failed");}
void Record(App&a,uint32_t i){auto c=a.commands[i];vkResetCommandBuffer(c,0);VkCommandBufferBeginInfo bi{VK_STRUCTURE_TYPE_COMMAND_BUFFER_BEGIN_INFO};vkBeginCommandBuffer(c,&bi);VkClearValue clear{{{0.02f,0.02f,0.04f,1}}};VkRenderPassBeginInfo rp{VK_STRUCTURE_TYPE_RENDER_PASS_BEGIN_INFO,nullptr,a.renderPass,a.framebuffers[i],{{0,0},a.extent},1,&clear};vkCmdBeginRenderPass(c,&rp,VK_SUBPASS_CONTENTS_INLINE);vkCmdBindPipeline(c,VK_PIPELINE_BIND_POINT_GRAPHICS,a.pipeline);float p[3]{(float)a.position.x,(float)a.position.y,(float)a.position.z};vkCmdPushConstants(c,a.pipelineLayout,VK_SHADER_STAGE_VERTEX_BIT,0,12,p);vkCmdDraw(c,3,1,0,0);vkCmdEndRenderPass(c);vkEndCommandBuffer(c);}
void Recreate(App&a){int w=0,h=0;while(!w||!h){RECT r;GetClientRect(a.window,&r);w=r.right;h=r.bottom;MSG m;while(PeekMessage(&m,nullptr,0,0,PM_REMOVE)){TranslateMessage(&m);DispatchMessage(&m);}}vkDeviceWaitIdle(a.device);for(auto semaphore:a.renderFinished)vkDestroySemaphore(a.device,semaphore,nullptr);a.renderFinished.clear();DestroySwap(a);CreateSwap(a);vkFreeCommandBuffers(a.device,a.commandPool,(uint32_t)a.commands.size(),a.commands.data());a.commands.clear();VkCommandBufferAllocateInfo al{VK_STRUCTURE_TYPE_COMMAND_BUFFER_ALLOCATE_INFO,nullptr,a.commandPool,VK_COMMAND_BUFFER_LEVEL_PRIMARY,(uint32_t)a.framebuffers.size()};a.commands.resize(a.framebuffers.size());a.Check(vkAllocateCommandBuffers(a.device,&al,a.commands.data()),"resize command allocation failed");VkSemaphoreCreateInfo si{VK_STRUCTURE_TYPE_SEMAPHORE_CREATE_INFO};a.renderFinished.resize(a.framebuffers.size());for(auto& semaphore:a.renderFinished)a.Check(vkCreateSemaphore(a.device,&si,nullptr,&semaphore),"resize semaphore failed");a.resized=false;a.Log("Swapchain recreated after resize");}
void Draw(App&a){vkWaitForFences(a.device,1,&a.inFlight,VK_TRUE,UINT64_MAX);uint32_t i;auto r=vkAcquireNextImageKHR(a.device,a.swapchain,UINT64_MAX,a.imageAvailable,{},&i);if(r==VK_ERROR_OUT_OF_DATE_KHR){Recreate(a);return;}a.Check(r,"acquire image failed");vkResetFences(a.device,1,&a.inFlight);Record(a,i);VkPipelineStageFlags stage=VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT;
  VkSubmitInfo s{VK_STRUCTURE_TYPE_SUBMIT_INFO};s.waitSemaphoreCount=1;s.pWaitSemaphores=&a.imageAvailable;s.pWaitDstStageMask=&stage;s.commandBufferCount=1;s.pCommandBuffers=&a.commands[i];s.signalSemaphoreCount=1;s.pSignalSemaphores=&a.renderFinished[i];
  a.Check(vkQueueSubmit(a.graphicsQueue,1,&s,a.inFlight),"submit failed");VkPresentInfoKHR p{VK_STRUCTURE_TYPE_PRESENT_INFO_KHR};p.waitSemaphoreCount=1;p.pWaitSemaphores=&a.renderFinished[i];p.swapchainCount=1;p.pSwapchains=&a.swapchain;p.pImageIndices=&i;r=vkQueuePresentKHR(a.presentQueue,&p);if(r==VK_ERROR_OUT_OF_DATE_KHR||r==VK_SUBOPTIMAL_KHR||a.resized)Recreate(a);else a.Check(r,"present failed");}
void Destroy(App&a){if(a.device)vkDeviceWaitIdle(a.device);if(a.device){if(a.inFlight)vkDestroyFence(a.device,a.inFlight,nullptr);for(auto semaphore:a.renderFinished)vkDestroySemaphore(a.device,semaphore,nullptr);if(a.imageAvailable)vkDestroySemaphore(a.device,a.imageAvailable,nullptr);if(a.commandPool)vkDestroyCommandPool(a.device,a.commandPool,nullptr);DestroySwap(a);vkDestroyDevice(a.device,nullptr);}if(a.surface)vkDestroySurfaceKHR(a.instance,a.surface,nullptr);
#ifdef NC_DEBUG_BUILD
  if(a.debug){auto fn=(PFN_vkDestroyDebugUtilsMessengerEXT)vkGetInstanceProcAddr(a.instance,"vkDestroyDebugUtilsMessengerEXT");if(fn)fn(a.instance,a.debug,nullptr);}
#endif
  if(a.instance)vkDestroyInstance(a.instance,nullptr);if(a.window)DestroyWindow(a.window);gApp=nullptr;}
}
extern "C" NC_API NcResult __cdecl nc_run_triangle(NcRelativePosition pos,NcDiagnosticCallback cb,void* data){if(!cb)return NC_INVALID_ARGUMENT;App a; a.callback=cb;a.callbackData=data;a.position=pos;try{gApp=&a;CreateNativeWindow(a);CreateInstance(a);CreateDebug(a);CreateSurface(a);PickDevice(a);CreateDevice(a);CreateSwap(a);CreateCommands(a);a.Log("Native-to-managed diagnostic callback is active");auto start=std::chrono::steady_clock::now();uint64_t frames=0;bool run=true;while(run){MSG m;while(PeekMessage(&m,nullptr,0,0,PM_REMOVE)){if(m.message==WM_QUIT)run=false;TranslateMessage(&m);DispatchMessage(&m);}if(run){Draw(a);frames++;if(std::chrono::steady_clock::now()-start>std::chrono::seconds(5))run=false;}}vkDeviceWaitIdle(a.device);auto ms=std::chrono::duration<double,std::milli>(std::chrono::steady_clock::now()-start).count()/std::max<uint64_t>(1,frames);char b[128];std::snprintf(b,sizeof b,"Average frame time: %.3f ms (%llu frames)",ms,(unsigned long long)frames);a.Log(b);Destroy(a);return NC_SUCCESS;}catch(const std::exception&e){a.Log(e.what());Destroy(a);return NC_FAILURE;}}
