namespace NovaCore.NaifEphemerisAdapter;
internal readonly record struct AdaptiveSamplingConfig(double MaxPositionMetres,double MaxVelocityMetresPerSecond,long MinimumSeconds,int MaximumDepth){internal bool IsValid=>MaxPositionMetres>0&&MaxVelocityMetresPerSecond>0&&MinimumSeconds>0&&MaximumDepth>=0;}
internal readonly record struct AdaptiveKnot(long Et,CspiceSourceState State);
internal readonly record struct AdaptiveSamplingResult(int BodyId,AdaptiveKnot[] Knots,double RmsPositionError,double RmsVelocityError,double MaxPositionError,long WorstPositionErrorEt,double MaxVelocityError,long WorstVelocityErrorEt,int MaximumDepth);
internal readonly record struct AdaptiveSeedCadenceSearchConfig(long MinimumSeedSeconds,long MaximumSeedSeconds,long ResolutionSeconds){internal bool IsValid=>MinimumSeedSeconds>0&&MaximumSeedSeconds>=MinimumSeedSeconds&&ResolutionSeconds>0&&(MaximumSeedSeconds-MinimumSeedSeconds)%ResolutionSeconds==0;}
internal readonly record struct AdaptiveSeedCadenceSearchResult(long LargestPassingSeedSeconds,long NextFailingSeedSeconds,AdaptiveSamplingResult Sample);
internal static class AdaptiveHermiteSampler
{
 internal static bool TrySample(CspiceSession s,int child,int parent,long start,long end,long seed,AdaptiveSamplingConfig c,out AdaptiveSamplingResult r){r=default;if(!c.IsValid||end<=start||seed<=0)return false;var cache=new SortedDictionary<long,CspiceSourceState>();var accepted=new SortedDictionary<long,CspiceSourceState>();var residuals=new List<Residual>();int order=0;bool Get(long t,out CspiceSourceState x){if(cache.TryGetValue(t,out x))return true;if(!s.TryQuery(child,t,out var a)||!s.TryQuery(parent,t,out var b)){x=default;return false;}x=new((a.X-b.X)*1000,(a.Y-b.Y)*1000,(a.Z-b.Z)*1000,(a.Vx-b.Vx)*1000,(a.Vy-b.Vy)*1000,(a.Vz-b.Vz)*1000);cache[t]=x;return true;}int depth=0;bool Walk(long a,long b,int d){if(!Get(a,out var x)||!Get(b,out var y))return false;depth=Math.Max(depth,d);var pass=true;foreach(var n in new[]{1,3,5,7}){var t=a+(b-a)*n/8;if(!Get(t,out var z))return false;var q=H(x,y,(double)(t-a)/(b-a),b-a);var pe=D(q,z,false);var ve=D(q,z,true);residuals.Add(new(t,pe,ve,order++));if(pe>c.MaxPositionMetres||ve>c.MaxVelocityMetresPerSecond)pass=false;}if(pass){accepted[a]=x;accepted[b]=y;return true;}if(d>=c.MaximumDepth||b-a<=c.MinimumSeconds)return false;var m=a+(b-a)/2;return Walk(a,m,d+1)&&Walk(m,b,d+1);}for(var a=start;a<end;){var b=Math.Min(a+seed,end);if(!Walk(a,b,0))return false;a=b;}residuals.Sort((left,right)=>{var compare=left.Et.CompareTo(right.Et);return compare!=0?compare:left.Order.CompareTo(right.Order);});double positionSquares=0,velocitySquares=0,maxPosition=0,maxVelocity=0;var worstPositionEt=start;var worstVelocityEt=start;foreach(var residual in residuals){positionSquares+=residual.Position*residual.Position;velocitySquares+=residual.Velocity*residual.Velocity;if(residual.Position>maxPosition){maxPosition=residual.Position;worstPositionEt=residual.Et;}if(residual.Velocity>maxVelocity){maxVelocity=residual.Velocity;worstVelocityEt=residual.Et;}}r=new(child,accepted.Select(p=>new AdaptiveKnot(p.Key,p.Value)).ToArray(),Math.Sqrt(positionSquares/residuals.Count),Math.Sqrt(velocitySquares/residuals.Count),maxPosition,worstPositionEt,maxVelocity,worstVelocityEt,depth);return true;}
 internal static bool TryFindLargestUniformSeed(CspiceSession s,int child,int parent,long start,long end,AdaptiveSamplingConfig c,AdaptiveSeedCadenceSearchConfig search,out AdaptiveSeedCadenceSearchResult r){r=default;if(!search.IsValid)return false;var uniform=c with{MaximumDepth=0};for(var seed=search.MaximumSeedSeconds;seed>=search.MinimumSeedSeconds;seed-=search.ResolutionSeconds)if(TrySample(s,child,parent,start,end,seed,uniform,out var sample)){var next=seed+search.ResolutionSeconds;if(next>search.MaximumSeedSeconds||TrySample(s,child,parent,start,end,next,uniform,out _))return false;r=new(seed,next,sample);return true;}return false;}
 static CspiceSourceState H(CspiceSourceState a,CspiceSourceState b,double u,double h){double P(double p,double v,double q,double w)=>(2*u*u*u-3*u*u+1)*p+(u*u*u-2*u*u+u)*h*v+(-2*u*u*u+3*u*u)*q+(u*u*u-u*u)*h*w;double V(double p,double v,double q,double w)=>(6*u*u-6*u)/h*p+(3*u*u-4*u+1)*v+(-6*u*u+6*u)/h*q+(3*u*u-2*u)*w;return new(P(a.X,a.Vx,b.X,b.Vx),P(a.Y,a.Vy,b.Y,b.Vy),P(a.Z,a.Vz,b.Z,b.Vz),V(a.X,a.Vx,b.X,b.Vx),V(a.Y,a.Vy,b.Y,b.Vy),V(a.Z,a.Vz,b.Z,b.Vz));}
 static double D(CspiceSourceState a,CspiceSourceState b,bool v){var x=(v?a.Vx:a.X)-(v?b.Vx:b.X);var y=(v?a.Vy:a.Y)-(v?b.Vy:b.Y);var z=(v?a.Vz:a.Z)-(v?b.Vz:b.Z);return Math.Sqrt(x*x+y*y+z*z);}
 readonly record struct Residual(long Et,double Position,double Velocity,int Order);
}
