using System.Security.Cryptography;

namespace NovaCore.NaifEphemerisAdapter;

internal enum NaifSourceRole : byte { PlanetaryLunarSpk, GravitationalConstants, PhysicalConstants, LeapSeconds, CspiceToolkit, TargetMap, ConversionPolicy }
internal enum NaifAdapterStatus : byte { Success, TemplateManifest, InvalidManifest, MissingRequiredInput, UnexpectedInput, HashMismatch, SizeMismatch, DuplicateRole, DuplicateFile, UnsupportedToolkit, InvalidTargetMap, SourceQueryFailure, NonFiniteSourceState, UnitConversionFailure, ParentRelativeFailure, PolicyHashMismatch }
internal enum NaifManifestReadiness : byte { Template, FullyPinned, Invalid }
internal readonly record struct NaifPinnedSource(NaifSourceRole Role,string CanonicalName,string Family,string Version,long ExpectedBytes,string Sha256,bool Required,string Purpose);
internal sealed record NaifSourceManifest(ushort Version,IReadOnlyList<NaifPinnedSource> Entries)
{ internal NaifManifestReadiness Readiness { get { if(Version!=1||Entries.Count!=5||Entries.Select(x=>x.Role).Distinct().Count()!=Entries.Count||Entries.Select(x=>x.CanonicalName).Distinct(StringComparer.Ordinal).Count()!=Entries.Count)return NaifManifestReadiness.Invalid; return Entries.All(x=>!string.IsNullOrWhiteSpace(x.CanonicalName)&&!string.IsNullOrWhiteSpace(x.Family)&&!string.IsNullOrWhiteSpace(x.Version)&&x.ExpectedBytes>0&&x.Sha256.Length==64&&x.Sha256.Any(c=>c!='0'))?NaifManifestReadiness.FullyPinned:NaifManifestReadiness.Template; } } internal bool IsValid=>Readiness!=NaifManifestReadiness.Invalid; }
internal readonly record struct NaifTargetMapEntry(ulong NovaBodyId,int NaifTargetId,ulong ParentBodyId,byte Classification,bool IsBarycenter,NaifSourceRole ConstantsRole);
internal sealed record NaifTargetMap(ushort Version,IReadOnlyList<NaifTargetMapEntry> Entries)
{ internal bool IsValid => Version==1&&Entries.Count==12&&Entries.Count(x=>x.ParentBodyId==0)==1&&Entries.Select(x=>x.NovaBodyId).Distinct().Count()==Entries.Count&&Entries.Select(x=>x.NaifTargetId).Distinct().Count()==Entries.Count; }
internal readonly record struct NaifQueryPolicy(int ObserverNaifId,string Frame,string Aberration,ulong TimeDomain,long DomainTicksPerSecond,long Start,long End)
{ internal bool IsValid => ObserverNaifId==0&&Frame=="J2000"&&Aberration=="NONE"&&TimeDomain!=0&&DomainTicksPerSecond==1_000_000&&Start<=End; }
internal readonly record struct NaifStateKm(int Target,long DomainTick,double X,double Y,double Z,double Vx,double Vy,double Vz)
{ internal bool IsFinite=>double.IsFinite(X)&&double.IsFinite(Y)&&double.IsFinite(Z)&&double.IsFinite(Vx)&&double.IsFinite(Vy)&&double.IsFinite(Vz); }
internal interface INaifStateVectorSource { NaifAdapterStatus TryGetState(int target,int observer,in NaifQueryPolicy policy,long domainTick,out NaifStateKm state); }
internal static class NaifContracts
{
 internal static NaifSourceManifest Manifest { get; }=new(1,[new(NaifSourceRole.PlanetaryLunarSpk,"de440.bsp","NAIF-DE440","DE440",119799808,"A4CE9BF9B3282BECC9F4B2AC3CEBE03A2AE7599981AABD7265FD8482FFF7C4B5",true,"planetary and lunar geometric states"),new(NaifSourceRole.GravitationalConstants,"gm_de440.tpc","NAIF","DE440",12406,"924DDF4FB9EAD9FE8A1AA55780BCABDE40B09D00065D58226E24B68D8092F140",true,"GM"),new(NaifSourceRole.PhysicalConstants,"pck00010.tpc","NAIF","PCK00010",126143,"59468328349AA730D18BF1F8D7E86EFE6E40B75DFB921908F99321B3A7A701D2",true,"shape and deterministic orientation fallback"),new(NaifSourceRole.PhysicalConstants,"moon_pa_de440_200625.bpc","NAIF-JPL","DE440",12863488,"60CD55AA401EA2EA97360636F567554BFE4E37BB829F901B4460A455DFAF783F",true,"offline high-precision lunar principal-axis orientation"),new(NaifSourceRole.PhysicalConstants,"moon_de440_250416.tf","NAIF-JPL","DE440",19478,"A47C71E9C9F33796BDAFB2C9D69A7EE447B6016ECAD80F71CD6F3E479F9CF768",true,"offline DE440 lunar frame chain"),new(NaifSourceRole.LeapSeconds,"naif0012.tls","NAIF","0012",5257,"678E32BDB5A744117A467CD9601CD6B373F0E9BC9BBDE1371D5EEE39600A039B",true,"offline UTC parsing"),new(NaifSourceRole.CspiceToolkit,"cspice.zip","NAIF-CSPICE","N0067",36519028,"98D60B814B412FA55294AEAAEB7DAB46D849CC87A8B709FFE835D08DE17625DC",true,"offline toolkit")]);
 internal static NaifTargetMap Targets { get; }=new(1,[new(1,0,0,8,true,NaifSourceRole.GravitationalConstants),new(2,10,1,0,false,NaifSourceRole.GravitationalConstants),new(3,1,1,1,true,NaifSourceRole.GravitationalConstants),new(4,2,1,1,true,NaifSourceRole.GravitationalConstants),new(5,3,1,8,true,NaifSourceRole.GravitationalConstants),new(6,399,5,1,false,NaifSourceRole.GravitationalConstants),new(7,301,5,3,false,NaifSourceRole.GravitationalConstants),new(8,4,1,1,true,NaifSourceRole.GravitationalConstants),new(9,5,1,1,true,NaifSourceRole.GravitationalConstants),new(10,6,1,1,true,NaifSourceRole.GravitationalConstants),new(11,7,1,1,true,NaifSourceRole.GravitationalConstants),new(12,8,1,1,true,NaifSourceRole.GravitationalConstants)]);
 internal static NaifQueryPolicy Policy=>new(0,"J2000","NONE",17,1_000_000,0,1_577_880_000_000_000);
 internal static NaifAdapterStatus TryVerify(NaifSourceManifest manifest,IReadOnlyDictionary<NaifSourceRole,byte[]> supplied){if(manifest.Readiness==NaifManifestReadiness.Invalid)return NaifAdapterStatus.InvalidManifest;if(manifest.Readiness==NaifManifestReadiness.Template)return NaifAdapterStatus.TemplateManifest;if(supplied.Count!=manifest.Entries.Count)return NaifAdapterStatus.UnexpectedInput;foreach(var e in manifest.Entries){if(!supplied.TryGetValue(e.Role,out var b))return NaifAdapterStatus.MissingRequiredInput;if(b.LongLength!=e.ExpectedBytes)return NaifAdapterStatus.SizeMismatch;if(!Convert.ToHexString(SHA256.HashData(b)).Equals(e.Sha256,StringComparison.OrdinalIgnoreCase))return NaifAdapterStatus.HashMismatch;}return NaifAdapterStatus.Success;}
 internal static bool TryParentRelative(in NaifStateKm child,in NaifStateKm parent,out NaifStateKm relative){relative=default;if(child.DomainTick!=parent.DomainTick||!child.IsFinite||!parent.IsFinite)return false;relative=new(child.Target,child.DomainTick,(child.X-parent.X)*1000,(child.Y-parent.Y)*1000,(child.Z-parent.Z)*1000,(child.Vx-parent.Vx)*1000,(child.Vy-parent.Vy)*1000,(child.Vz-parent.Vz)*1000);return relative.IsFinite;}
 internal static ulong HashPolicy(){var b=System.Text.Encoding.UTF8.GetBytes("DE440|SSB|J2000|NONE|TDBET|1000000|SI|child-parent|v1");ulong h=14695981039346656037;foreach(var x in b){h^=x;h*=1099511628211;}return h;}
}
