<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <PlatformTarget>x64</PlatformTarget>
    <RootNamespace>NovaCore.Launcher</RootNamespace>
    <AssemblyName>NovaCore.Launcher</AssemblyName>
  </PropertyGroup>
</Project>
