using System.Buffers.Binary;
using System.Text;

namespace NovaCore.EphemerisFormat;

/// <summary>Self-describing NCPE v2 semantic definition. It contains no runtime object references.</summary>
public sealed record NcpeV2Definition(NcpeV2System System, IReadOnlyList<NcpeV2Source> Sources, IReadOnlyList<NcpeV2Body> Bodies, IReadOnlyList<NcpeV2Binding> Bindings, IReadOnlyList<NcpeV2Payload> Payloads, IReadOnlyList<NormalizedEphemerisSample> Samples);
public readonly record struct NcpeV2System(ulong SystemId,long SimulationAnchor,long DomainAnchor,long DomainTicksPerSecond,long ScaleNumerator,long ScaleDenominator,ulong SourceId,ulong SourceVersion,ulong DomainId,long CoverageStart,long CoverageEnd,ulong FrameId,ulong ConstantsVersion,ulong ContentHashHigh,ulong ContentHashLow,ulong AuthoredHashHigh,ulong AuthoredHashLow,ulong ConverterId,ulong ConverterVersion,ulong ConversionPolicyHash);
public readonly record struct NcpeV2Source(ulong Id,byte Model,ulong Version,ulong DomainId,long CoverageStart,long CoverageEnd,ulong FrameId,ulong ConstantsVersion,ulong ContentHashHigh,ulong ContentHashLow,ulong AuthoredHashHigh,ulong AuthoredHashLow);
public sealed record NcpeV2Body(ulong Id,string Name,byte Classification,ulong ParentId,ulong RotationReference,ulong AtmosphereReference,ulong VisualReference,IReadOnlyList<string> Aliases,double Mu,double MeanRadius,double EquatorialRadius,double PolarRadius,double Flattening,ulong SiderealReference,ulong PhysicalAtmosphereReference,ulong PhysicalVisualReference,ulong PhysicalSource,ulong PhysicalConstantsVersion);
public readonly record struct NcpeV2Binding(ulong BodyId,byte Model,ulong SourceId,int PayloadIndex, double FixedPositionX,double FixedPositionY,double FixedPositionZ,double FixedVelocityX,double FixedVelocityY,double FixedVelocityZ,double FixedQuaternionX,double FixedQuaternionY,double FixedQuaternionZ,double FixedQuaternionW,double FixedAngularVelocityX,double FixedAngularVelocityY,double FixedAngularVelocityZ);
public readonly record struct NcpeV2Payload(ulong DomainId,int FirstSampleIndex,int SampleCount,byte Interpolation,long CoverageStart,long CoverageEnd);
public enum NcpeV2Status : byte { Success, UnsupportedV1Reconstruction, InvalidMagic, InvalidVersion, Truncated, InvalidSection, MissingSection, InvalidSemanticData, HashMismatch, ExpectedDefinitionHashMismatch }

public static class NcpeV2Codec
{
    public const uint Magic = 0x4550434E; public const ushort Version = 2;
    private const uint SystemSection=1,SourceSection=2,BodySection=3,BindingSection=4,PayloadSection=5,SampleSection=6,HashSection=7;
    public static NcpeV2Status TryWrite(NcpeV2Definition value,out byte[]? bytes)
    {
        bytes=null; if(!Validate(value)) return NcpeV2Status.InvalidSemanticData;
        var sections=new[]{Section( SystemSection,w=>WriteSystem(w,value.System)),Section(SourceSection,w=>WriteSources(w,value.Sources)),Section(BodySection,w=>WriteBodies(w,value.Bodies)),Section(BindingSection,w=>WriteBindings(w,value.Bindings)),Section(PayloadSection,w=>WritePayloads(w,value.Payloads)),Section(SampleSection,w=>WriteSamples(w,value.Samples))};
        var expected=NcpeV2SemanticHash.Compute(value); sections=sections.Append(Section(HashSection,w=>{w.Write(expected);w.Write(value.System.ConversionPolicyHash);})).ToArray();
        var length=24+sections.Sum(x=>8+x.Data.Length)+16; var b=new byte[length]; W32(b,0,Magic);W16(b,4,Version);W32(b,8,0x01020304);W32(b,12,(uint)length);W32(b,16,(uint)sections.Length);var o=24;foreach(var s in sections){W32(b,o,s.Id);W32(b,o+4,(uint)s.Data.Length);o+=8;s.Data.CopyTo(b,o);o+=s.Data.Length;}var artifact=EphemerisHash.Compute(b.AsSpan(0,length-16)).Value;W64(b,length-16,artifact);W64(b,length-8,expected);bytes=b;return NcpeV2Status.Success;
    }
    public static NcpeV2Status TryRead(ReadOnlySpan<byte> bytes,out NcpeV2Definition? value,out ulong artifactHash,out ulong expectedDefinitionHash)
    {
        value=null;artifactHash=expectedDefinitionHash=0;if(bytes.Length<40)return NcpeV2Status.Truncated;if(R32(bytes,0)!=Magic)return NcpeV2Status.InvalidMagic;var version=R16(bytes,4);if(version==1)return NcpeV2Status.UnsupportedV1Reconstruction;if(version!=Version)return NcpeV2Status.InvalidVersion;if(R32(bytes,8)!=0x01020304||R32(bytes,12)!=bytes.Length)return NcpeV2Status.InvalidSection;if(EphemerisHash.Compute(bytes[..^16]).Value!=R64(bytes,bytes.Length-16))return NcpeV2Status.HashMismatch;
        var dict=new Dictionary<uint,ReadOnlyMemory<byte>>();var count=R32(bytes,16);var o=24;var copy=bytes.ToArray();for(var i=0u;i<count;i++){if(o>bytes.Length-24)return NcpeV2Status.Truncated;var id=R32(bytes,o);var len=R32(bytes,o+4);o+=8;if(len>bytes.Length-16-o||!dict.TryAdd(id,copy.AsMemory(o,(int)len)))return NcpeV2Status.InvalidSection;o+=(int)len;}if(o!=bytes.Length-16||dict.Count!=7||!dict.Keys.All(x=>x is >=SystemSection and <=HashSection))return NcpeV2Status.MissingSection;
        try{var system=ReadSystem(dict[SystemSection].Span);var sources=ReadSources(dict[SourceSection].Span);var bodies=ReadBodies(dict[BodySection].Span);var bindings=ReadBindings(dict[BindingSection].Span);var payloads=ReadPayloads(dict[PayloadSection].Span);var samples=ReadSamples(dict[SampleSection].Span);value=new(system,sources,bodies,bindings,payloads,samples);expectedDefinitionHash=R64(dict[HashSection].Span,0);artifactHash=R64(bytes,bytes.Length-16);if(!Validate(value))return NcpeV2Status.InvalidSemanticData;if(NcpeV2SemanticHash.Compute(value)!=expectedDefinitionHash)return NcpeV2Status.ExpectedDefinitionHashMismatch;return NcpeV2Status.Success;}catch(EndOfStreamException){value=null;return NcpeV2Status.Truncated;}catch(ArgumentException){value=null;return NcpeV2Status.InvalidSection;}
    }
    private static bool Validate(NcpeV2Definition d){if(d.System.SystemId==0||d.System.DomainId==0||d.System.DomainTicksPerSecond<=0||d.System.ScaleNumerator<=0||d.System.ScaleDenominator<=0||d.System.CoverageStart>d.System.CoverageEnd||d.Bodies.Count==0||d.Bindings.Count!=d.Bodies.Count)return false;var ids=new HashSet<ulong>();var roots=0;foreach(var b in d.Bodies){if(!ids.Add(b.Id)||b.Id==0||string.IsNullOrWhiteSpace(b.Name)||b.Classification>8||!double.IsFinite(b.Mu)||!double.IsFinite(b.MeanRadius)||!double.IsFinite(b.EquatorialRadius)||!double.IsFinite(b.PolarRadius)||!double.IsFinite(b.Flattening))return false;if(b.ParentId==0)roots++;}if(roots!=1)return false;foreach(var b in d.Bodies)if(b.ParentId!=0&&!ids.Contains(b.ParentId))return false;foreach(var p in d.Payloads){if(p.DomainId!=d.System.DomainId||p.FirstSampleIndex<0||p.SampleCount<2||p.FirstSampleIndex+p.SampleCount>d.Samples.Count||p.Interpolation!=1)return false;}foreach(var s in d.Samples)if(!s.IsFinite)return false;return d.Bindings.All(x=>ids.Contains(x.BodyId)&&d.Sources.Any(s=>s.Id==x.SourceId&&s.Model==x.Model));}
    private static (uint Id,byte[] Data) Section(uint id,Action<BinaryWriter>w){using var stream=new MemoryStream();using(var writer=new BinaryWriter(stream,Encoding.UTF8,true))w(writer);return(id,stream.ToArray());}
    private static void WriteSystem(BinaryWriter w,NcpeV2System x){foreach(var v in new ulong[]{x.SystemId,unchecked((ulong)x.SimulationAnchor),unchecked((ulong)x.DomainAnchor),unchecked((ulong)x.DomainTicksPerSecond),unchecked((ulong)x.ScaleNumerator),unchecked((ulong)x.ScaleDenominator),x.SourceId,x.SourceVersion,x.DomainId,unchecked((ulong)x.CoverageStart),unchecked((ulong)x.CoverageEnd),x.FrameId,x.ConstantsVersion,x.ContentHashHigh,x.ContentHashLow,x.AuthoredHashHigh,x.AuthoredHashLow,x.ConverterId,x.ConverterVersion,x.ConversionPolicyHash})w.Write(v);}
    private static NcpeV2System ReadSystem(ReadOnlySpan<byte>b){if(b.Length!=160)throw new ArgumentException();var v=new ulong[20];for(var i=0;i<20;i++)v[i]=R64(b,i*8);return new(v[0],unchecked((long)v[1]),unchecked((long)v[2]),unchecked((long)v[3]),unchecked((long)v[4]),unchecked((long)v[5]),v[6],v[7],v[8],unchecked((long)v[9]),unchecked((long)v[10]),v[11],v[12],v[13],v[14],v[15],v[16],v[17],v[18],v[19]);}
    private static void WriteSources(BinaryWriter w,IReadOnlyList<NcpeV2Source>x){w.Write(x.Count);foreach(var s in x){w.Write(s.Id);w.Write(s.Model);w.Write(s.Version);w.Write(s.DomainId);w.Write(s.CoverageStart);w.Write(s.CoverageEnd);w.Write(s.FrameId);w.Write(s.ConstantsVersion);w.Write(s.ContentHashHigh);w.Write(s.ContentHashLow);w.Write(s.AuthoredHashHigh);w.Write(s.AuthoredHashLow);}}
    private static List<NcpeV2Source> ReadSources(ReadOnlySpan<byte>b){using var r=new BinaryReader(new MemoryStream(b.ToArray()));var n=r.ReadInt32();var x=new List<NcpeV2Source>(n);for(var i=0;i<n;i++)x.Add(new(r.ReadUInt64(),r.ReadByte(),r.ReadUInt64(),r.ReadUInt64(),r.ReadInt64(),r.ReadInt64(),r.ReadUInt64(),r.ReadUInt64(),r.ReadUInt64(),r.ReadUInt64(),r.ReadUInt64(),r.ReadUInt64()));return x;}
    private static void WriteBodies(BinaryWriter w,IReadOnlyList<NcpeV2Body>x){w.Write(x.Count);foreach(var b in x){w.Write(b.Id);w.Write(b.Name);w.Write(b.Classification);w.Write(b.ParentId);w.Write(b.RotationReference);w.Write(b.AtmosphereReference);w.Write(b.VisualReference);w.Write(b.Aliases.Count);foreach(var a in b.Aliases)w.Write(a);foreach(var v in new[]{b.Mu,b.MeanRadius,b.EquatorialRadius,b.PolarRadius,b.Flattening})w.Write(BitConverter.DoubleToInt64Bits(v));w.Write(b.SiderealReference);w.Write(b.PhysicalAtmosphereReference);w.Write(b.PhysicalVisualReference);w.Write(b.PhysicalSource);w.Write(b.PhysicalConstantsVersion);}}
    private static List<NcpeV2Body> ReadBodies(ReadOnlySpan<byte>b){using var r=new BinaryReader(new MemoryStream(b.ToArray()),Encoding.UTF8);var n=r.ReadInt32();var x=new List<NcpeV2Body>(n);for(var i=0;i<n;i++){var id=r.ReadUInt64();var name=r.ReadString();var c=r.ReadByte();var parent=r.ReadUInt64();var rot=r.ReadUInt64();var atm=r.ReadUInt64();var vis=r.ReadUInt64();var ac=r.ReadInt32();var a=new string[ac];for(var j=0;j<ac;j++)a[j]=r.ReadString();double D()=>BitConverter.Int64BitsToDouble(r.ReadInt64());x.Add(new(id,name,c,parent,rot,atm,vis,a,D(),D(),D(),D(),D(),r.ReadUInt64(),r.ReadUInt64(),r.ReadUInt64(),r.ReadUInt64(),r.ReadUInt64()));}return x;}
    private static void WriteBindings(BinaryWriter w,IReadOnlyList<NcpeV2Binding>x){w.Write(x.Count);foreach(var v in x){w.Write(v.BodyId);w.Write(v.Model);w.Write(v.SourceId);w.Write(v.PayloadIndex);foreach(var d in new[]{v.FixedPositionX,v.FixedPositionY,v.FixedPositionZ,v.FixedVelocityX,v.FixedVelocityY,v.FixedVelocityZ,v.FixedQuaternionX,v.FixedQuaternionY,v.FixedQuaternionZ,v.FixedQuaternionW,v.FixedAngularVelocityX,v.FixedAngularVelocityY,v.FixedAngularVelocityZ})w.Write(BitConverter.DoubleToInt64Bits(d));}}
    private static List<NcpeV2Binding> ReadBindings(ReadOnlySpan<byte>b){using var r=new BinaryReader(new MemoryStream(b.ToArray()));var n=r.ReadInt32();var x=new List<NcpeV2Binding>(n);for(var i=0;i<n;i++){var id=r.ReadUInt64();var m=r.ReadByte();var s=r.ReadUInt64();var p=r.ReadInt32();double D()=>BitConverter.Int64BitsToDouble(r.ReadInt64());x.Add(new(id,m,s,p,D(),D(),D(),D(),D(),D(),D(),D(),D(),D(),D(),D(),D()));}return x;}
    private static void WritePayloads(BinaryWriter w,IReadOnlyList<NcpeV2Payload>x){w.Write(x.Count);foreach(var p in x){w.Write(p.DomainId);w.Write(p.FirstSampleIndex);w.Write(p.SampleCount);w.Write(p.Interpolation);w.Write(p.CoverageStart);w.Write(p.CoverageEnd);}}
    private static List<NcpeV2Payload> ReadPayloads(ReadOnlySpan<byte>b){using var r=new BinaryReader(new MemoryStream(b.ToArray()));var n=r.ReadInt32();var x=new List<NcpeV2Payload>(n);for(var i=0;i<n;i++)x.Add(new(r.ReadUInt64(),r.ReadInt32(),r.ReadInt32(),r.ReadByte(),r.ReadInt64(),r.ReadInt64()));return x;}
    private static void WriteSamples(BinaryWriter w,IReadOnlyList<NormalizedEphemerisSample>x){w.Write(x.Count);foreach(var s in x){w.Write(s.DomainTick);foreach(var d in new[]{s.PositionX,s.PositionY,s.PositionZ,s.VelocityX,s.VelocityY,s.VelocityZ})w.Write(BitConverter.DoubleToInt64Bits(d));}}
    private static List<NormalizedEphemerisSample> ReadSamples(ReadOnlySpan<byte>b){using var r=new BinaryReader(new MemoryStream(b.ToArray()));var n=r.ReadInt32();var x=new List<NormalizedEphemerisSample>(n);for(var i=0;i<n;i++){var t=r.ReadInt64();double D()=>BitConverter.Int64BitsToDouble(r.ReadInt64());x.Add(new(t,D(),D(),D(),D(),D(),D()));}return x;}
    private static uint R32(ReadOnlySpan<byte>b,int o)=>BinaryPrimitives.ReadUInt32LittleEndian(b.Slice(o,4));private static ushort R16(ReadOnlySpan<byte>b,int o)=>BinaryPrimitives.ReadUInt16LittleEndian(b.Slice(o,2));private static ulong R64(ReadOnlySpan<byte>b,int o)=>BinaryPrimitives.ReadUInt64LittleEndian(b.Slice(o,8));private static void W32(byte[]b,int o,uint x)=>BinaryPrimitives.WriteUInt32LittleEndian(b.AsSpan(o,4),x);private static void W16(byte[]b,int o,ushort x)=>BinaryPrimitives.WriteUInt16LittleEndian(b.AsSpan(o,2),x);private static void W64(byte[]b,int o,ulong x)=>BinaryPrimitives.WriteUInt64LittleEndian(b.AsSpan(o,8),x);
}
public static class NcpeV2SemanticHash
{ public static ulong Compute(NcpeV2Definition d){ulong h=14695981039346656037UL;void M(ulong x){for(var i=0;i<8;i++){h^=(byte)x;h*=1099511628211UL;x>>=8;}}void S(string x){M((ulong)x.Length);foreach(var c in x)M(c);}var z=d.System;foreach(var x in new[]{z.SystemId,unchecked((ulong)z.SimulationAnchor),z.DomainId,unchecked((ulong)z.DomainAnchor),unchecked((ulong)z.DomainTicksPerSecond),unchecked((ulong)z.ScaleNumerator),unchecked((ulong)z.ScaleDenominator),z.SourceId,z.SourceVersion,z.FrameId,z.ConstantsVersion,z.ContentHashHigh,z.ContentHashLow,z.AuthoredHashHigh,z.AuthoredHashLow})M(x);M((ulong)d.Bodies.Count);foreach(var b in d.Bodies){M(b.Id);S(b.Name);M(b.Classification);M(b.ParentId);M(b.RotationReference);M(b.AtmosphereReference);M(b.VisualReference);M((ulong)b.Aliases.Count);foreach(var a in b.Aliases)S(a);foreach(var v in new[]{b.Mu,b.MeanRadius,b.EquatorialRadius,b.PolarRadius,b.Flattening})M(unchecked((ulong)BitConverter.DoubleToInt64Bits(v)));M(b.SiderealReference);M(b.PhysicalAtmosphereReference);M(b.PhysicalVisualReference);M(b.PhysicalSource);M(b.PhysicalConstantsVersion);}M((ulong)d.Sources.Count);foreach(var s in d.Sources)foreach(var x in new[]{s.Id,(ulong)s.Model,s.Id,s.Version,s.DomainId,unchecked((ulong)s.CoverageStart),unchecked((ulong)s.CoverageEnd),s.FrameId,s.ConstantsVersion,s.ContentHashHigh,s.ContentHashLow,s.AuthoredHashHigh,s.AuthoredHashLow})M(x);M(0);M(0);M(0);M((ulong)d.Payloads.Count);foreach(var p in d.Payloads)foreach(var x in new[]{p.DomainId,unchecked((ulong)p.FirstSampleIndex),unchecked((ulong)p.SampleCount),(ulong)p.Interpolation,unchecked((ulong)p.CoverageStart),unchecked((ulong)p.CoverageEnd)})M(x);M((ulong)d.Samples.Count);foreach(var s in d.Samples){M(unchecked((ulong)s.DomainTick));foreach(var v in new[]{s.PositionX,s.PositionY,s.PositionZ,s.VelocityX,s.VelocityY,s.VelocityZ})M(unchecked((ulong)BitConverter.DoubleToInt64Bits(v)));}foreach(var b in d.Bindings.OrderBy(x=>x.BodyId)){M(b.BodyId);M(b.Model);M(b.SourceId);M(unchecked((ulong)b.PayloadIndex));}return h;}}
