<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><OutputType>Exe</OutputType></PropertyGroup><ItemGroup><ProjectReference Include="..\..\src\NovaCore.Simulation\NovaCore.Simulation.csproj" /><None Update="Data\Assembly*-Reference-Endpoints.json" CopyToOutputDirectory="PreserveNewest" /></ItemGroup></Project>
