using NovaCore.EphemerisFormat;
using NovaCore.Simulation.Celestial;

var input = Fixture();
Check(NcpeV2Codec.TryWrite(V2Fixture(), out var v2) == NcpeV2Status.Success && v2 is not null, "v2 build");
Check(NcpeV2Codec.TryRead(v2!, out var decoded, out _, out var expectedHash) == NcpeV2Status.Success && decoded is not null && expectedHash == NcpeV2RuntimeHash.Compute(decoded), "v2 self description/hash");
var load=NcpeCelestialSystemLoader.TryRead(v2!, out var runtime); if(!load.Succeeded || runtime is null) throw new InvalidOperationException($"runtime load {load.Status} expected=0x{expectedHash:X16}"); Check(CelestialSystemDefinitionHash.Compute(runtime) == expectedHash, $"runtime reconstruction three-way hash expected=0x{expectedHash:X16} actual=0x{CelestialSystemDefinitionHash.Compute(runtime):X16}");
var runtimeHash = CelestialSystemDefinitionHash.Compute(runtime!); var clean = v2!.ToArray(); v2![100] ^= 1; Check(CelestialSystemDefinitionHash.Compute(runtime!) == runtimeHash, "caller buffer defensive copy");
void RejectFormat(Action<byte[]> corrupt,string name){var x=clean.ToArray();corrupt(x);Check(NcpeCelestialSystemLoader.TryRead(x,out _).Status==NcpeCelestialSystemLoadStatus.FormatFailure,name);}
RejectFormat(x=>x[0]^=1,"wrong magic"); RejectFormat(x=>x[4]=3,"unsupported version"); RejectFormat(x=>x[8]^=1,"endian marker"); Check(NcpeCelestialSystemLoader.TryRead(clean.AsSpan(0,20),out _).Status==NcpeCelestialSystemLoadStatus.FormatFailure,"truncated header"); RejectFormat(x=>x[12]^=1,"total length"); RejectFormat(x=>x[^16]^=1,"artifact hash");
Check(NcpeV2Codec.TryWrite(V2Fixture() with { System=V2Fixture().System with { SystemId=0 } },out _) == NcpeV2Status.InvalidSemanticData,"invalid system id");
Check(NcpeV2Codec.TryWrite(V2Fixture() with { Bodies=[..V2Fixture().Bodies, V2Fixture().Bodies[0]] },out _) == NcpeV2Status.InvalidSemanticData,"duplicate body");
var beforeLoad=GC.GetAllocatedBytesForCurrentThread(); var measured=NcpeCelestialSystemLoader.TryRead(clean,out var measuredDefinition); var loadAllocation=GC.GetAllocatedBytesForCurrentThread()-beforeLoad;Check(measured.Succeeded&&measuredDefinition is not null,"measured load");var beforeHash=GC.GetAllocatedBytesForCurrentThread();for(var i=0;i<1000;i++)_ = CelestialSystemDefinitionHash.Compute(measuredDefinition!);var postLoadAllocation=GC.GetAllocatedBytesForCurrentThread()-beforeHash;Check(postLoadAllocation==0,"post-load hash allocation");Console.WriteLine($"NCPE v2 runtime loader: artifact=0x{EphemerisHash.Compute(clean.AsSpan(0,clean.Length-16))}; definition=0x{runtimeHash:X16}; evaluation=not-applicable; load={loadAllocation} bytes; postLoadHash={postLoadAllocation} bytes");
var v1 = new byte[40]; System.Buffers.Binary.BinaryPrimitives.WriteUInt32LittleEndian(v1, 0x4550434E); System.Buffers.Binary.BinaryPrimitives.WriteUInt16LittleEndian(v1.AsSpan(4), 1); Check(NcpeV2Codec.TryRead(v1,out _,out _,out _) == NcpeV2Status.UnsupportedV1Reconstruction,"v1 controlled compatibility");
Check(EphemerisArtifactCodec.TryBuild(input, out var first) == EphemerisArtifactStatus.Success && first is not null, "build");
Check(EphemerisArtifactCodec.TryBuild(input with { Bodies = input.Bodies.Reverse().ToArray() }, out var reordered) == EphemerisArtifactStatus.Success && reordered is not null && first!.Bytes.SequenceEqual(reordered.Bytes), "canonical order");
Check(EphemerisArtifactCodec.TryRead(first!.Bytes, out var roundTrip) == EphemerisArtifactStatus.Success && roundTrip is not null && first.Bytes.SequenceEqual(roundTrip.Bytes), "round trip");
var altered=first.Bytes.ToArray(); altered[40]^=1; Check(EphemerisArtifactCodec.TryRead(altered,out _) == EphemerisArtifactStatus.HashMismatch,"hash mismatch");
var duplicate=input with { Bodies=[..input.Bodies, input.Bodies[0]]}; Check(EphemerisArtifactCodec.TryBuild(duplicate,out _) == EphemerisArtifactStatus.InvalidMetadata,"duplicate body");
var before=GC.GetAllocatedBytesForCurrentThread(); ulong hash=0; for(var i=0;i<1000;i++)hash^=EphemerisHash.Compute(first.Bytes).Value; var allocated=GC.GetAllocatedBytesForCurrentThread()-before; Console.WriteLine($"Ephemeris format: PASS hash=0x{first.Manifest.ArtifactHash} warmHashAllocation={allocated} bytes"); return 0;
static void Check(bool value,string name){if(!value)throw new InvalidOperationException(name);}
static NormalizedEphemerisInput Fixture()=>new(1,2,3,4,5,6,7,8,-20,20,9,10,[Body(1,0,0),Body(2,1,10),Body(3,1,-10)]);
static NormalizedEphemerisBody Body(ulong id,ulong parent,double d)=>new(id,parent,id,EphemerisInterpolationModel.CubicHermitePositionVelocityV1,[new(-20,d-20,1,2,1,0,0),new(-5,d-5,2,3,1,0,0),new(5,d+5,3,4,1,0,0),new(20,d+20,4,5,1,0,0)],.1,.01);
static NcpeV2Definition V2Fixture(){var s=new[]{new NormalizedEphemerisSample(-20,-20,1,2,1,0,0),new(-5,-5,2,3,1,0,0),new(5,5,3,4,1,0,0),new(20,20,4,5,1,0,0),new(-20,-10,1,2,1,0,0),new(-5,5,2,3,1,0,0),new(5,15,3,4,1,0,0),new(20,30,4,5,1,0,0)};var sys=new NcpeV2System(9001,0,0,1,1,1,71,2,17,-20,20,23,29,1,2,3,4,9002,2,0x5A5A);var src=new[]{new NcpeV2Source(71,1,2,17,-20,20,23,29,1,2,3,4),new NcpeV2Source(72,3,2,17,-20,20,23,29,1,2,3,4)};NcpeV2Body B(ulong id,string n,byte c,ulong p)=>new(id,n,c,p,0,0,0,Array.Empty<string>(),1,1,1,1,0,0,0,0,0,0);var bind=new[]{new NcpeV2Binding(1,1,71,0,0,0,0,0,0,0,0,0,0,1,0,0,0),new NcpeV2Binding(2,3,72,0,0,0,0,0,0,0,0,0,0,1,0,0,0),new NcpeV2Binding(3,3,72,1,0,0,0,0,0,0,0,0,0,1,0,0,0)};return new(sys,src,new[]{B(1,"Root",0,0),B(2,"Alpha",7,1),B(3,"Beta",7,1)},bind,new[]{new NcpeV2Payload(17,0,4,1,-20,20),new NcpeV2Payload(17,4,4,1,-20,20)},s);}
