using System.Runtime.InteropServices;
using NovaCore.Core;
using NovaCore.Graphics;
using NovaCore.Interop;

var tests=new (string,Action)[]{("MeshHandle",MeshHandleTest),("Transport layout",LayoutTest),("Transform conversion",TransformTest),("Camera relative",RelativeTest),("Batches and capacity",BatchTest)};
foreach(var (name,test) in tests){test();Console.WriteLine($"PASS {name}");}

static void MeshHandleTest(){Check(!MeshHandle.Invalid.IsValid,"zero invalid");Check(MeshHandle.Triangle.IsValid,"triangle valid");}
static void LayoutTest(){Check(Marshal.SizeOf<NativeEncodedPosition>()==32,"encoded size");Check(Marshal.SizeOf<NativeRenderTransform>()==32,"transform size");Check(Marshal.SizeOf<NativeRenderObject>()==80,"object stride");Check(Marshal.OffsetOf<NativeRenderObject>(nameof(NativeRenderObject.Position)).ToInt32()==0,"position offset");Check(Marshal.OffsetOf<NativeRenderObject>(nameof(NativeRenderObject.Transform)).ToInt32()==32,"transform offset");Check(Marshal.OffsetOf<NativeRenderObject>(nameof(NativeRenderObject.Mesh)).ToInt32()==64,"mesh offset");Check(Marshal.SizeOf<NativeDrawBatch>()==16,"batch stride");Check(NativeRuntime.GetAbiLayout(out var abi)==NativeResult.Success&&abi.RenderObjectSize==80&&abi.RenderObjectTransformOffset==32&&abi.RenderObjectMeshOffset==64,"native ABI layout");}
static void TransformTest(){var t=RenderTransform.FromAuthoritative(new DoubleQuaternion(0,0,Math.Sqrt(.5),Math.Sqrt(.5)),new Double3(-1,2,3));Check(t.Rotation.W>.7f&&t.Scale.X==-1,"conversion/negative scale policy");Check(FloatQuaternion.Identity==new FloatQuaternion(0,0,0,1),"identity");}
static void RelativeTest(){var camera=EncodedPosition.Encode(new Double3(4e12,-3e12,7e12));var positive=EncodedPosition.Resolve(EncodedPosition.Encode(new Double3(4e12+.25,-3e12,7e12)),camera);var negative=EncodedPosition.Resolve(EncodedPosition.Encode(new Double3(4e12-.25,-3e12,7e12)),camera);Check(positive.Value.X>0&&negative.Value.X<0,"relative signs");}
static void BatchTest(){var frame=new ReferenceFrameId(1);var camera=new RenderOrigin(new UniversePosition(new Double3(4e12,0,0),frame));var s=new RenderFrameSubmission(1000);s.Begin(camera);for(var i=0;i<1000;i++)s.Add(new UniversePosition(new Double3(4e12+i,0,0),frame),new DoubleQuaternion(0,0,0,1),new Double3(1,1,1),MeshHandle.Triangle);s.Complete();Check(s.ObjectCount==1000&&s.BatchCount==1&&s.Batches[0].ObjectCount==1000,"automatic stable batch");var small=new RenderFrameSubmission(1);small.Begin(camera);small.Add(camera.CameraPosition,new DoubleQuaternion(0,0,0,1),new Double3(1,1,1),MeshHandle.Triangle);try{small.Add(camera.CameraPosition,new DoubleQuaternion(0,0,0,1),new Double3(1,1,1),MeshHandle.Triangle);throw new Exception("capacity not rejected");}catch(InvalidOperationException){}var invalid=new RenderFrameSubmission(2);invalid.Begin(camera);try{invalid.Add(camera.CameraPosition,new DoubleQuaternion(0,0,0,1),new Double3(1,1,1),MeshHandle.Invalid);throw new Exception("invalid mesh not rejected");}catch(ArgumentOutOfRangeException){}}
static void Check(bool condition,string message){if(!condition)throw new Exception(message);}
